#!/bin/bash
#!/bin/bash

# Gera um número aleatório entre 1 e 1000 e armazena na variável numero
numero=$(( 1 + $RANDOM % 1000 ))

# Inicializa o contador de tentativas
tentativas=1

# Imprime a mensagem inicial e solicita o primeiro chute
echo "$numero Escolha um número entre 1 e 1000:"
read chute

# Loop que continua enquanto o chute for diferente do número secreto
while [ $numero -ne $chute ]; do
    # Verifica se o chute é maior que o número secreto
    if [ $numero -gt $chute ]; then
        echo "O número que você escolheu é maior que o número secreto"
    # Caso contrário, o chute é menor
    else
        echo "O número que você escolheu é menor que o número secreto"
    fi

    # Solicita um novo chute
    echo "Escolha um número entre 1 e 1000: "
    read chute

    # Incrementa o contador de tentativas
    ((tentativas++))
done

# Imprime a mensagem final com o número de tentativas
echo "você acertou em $tentativas tentativas!"
